package dev.vio.recommendations_service.service;

public enum Genre {
    DRAMA, COMEDY, ROMANCE, CRIME, DOCUMENTARY, THRILLER, MYSTERY, ACTION, MUSICAL, HORROR, ADVENTURE, ANIMATION, FANTASY, WAR, CHILDREN, WESTERN
}
